{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.7.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"# This Python 3 environment comes with many helpful analytics libraries installed\n# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python\n# For example, here's several helpful packages to load\n\nimport numpy as np # linear algebra\nimport pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n\n# Input data files are available in the read-only \"../input/\" directory\n# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n\nimport os\nfor dirname, _, filenames in os.walk('/kaggle/input'):\n    for filename in filenames:\n        print(os.path.join(dirname, filename))\n\n# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \"Save & Run All\" \n# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2023-01-10T12:11:10.345306Z","iopub.execute_input":"2023-01-10T12:11:10.346277Z","iopub.status.idle":"2023-01-10T12:11:10.372861Z","shell.execute_reply.started":"2023-01-10T12:11:10.346175Z","shell.execute_reply":"2023-01-10T12:11:10.371637Z"},"trusted":true},"execution_count":1,"outputs":[]},{"cell_type":"code","source":"import unittest","metadata":{"execution":{"iopub.status.busy":"2023-01-11T08:14:37.512968Z","iopub.execute_input":"2023-01-11T08:14:37.513797Z","iopub.status.idle":"2023-01-11T08:14:37.552677Z","shell.execute_reply.started":"2023-01-11T08:14:37.513649Z","shell.execute_reply":"2023-01-11T08:14:37.551286Z"},"trusted":true},"execution_count":1,"outputs":[]},{"cell_type":"code","source":"import unittest\n\nclass TestInventory(unittest.TestCase):\n    def setUp(self):\n        self.inventory = Inventory()\n\n    def test_add_product(self):\n        self.inventory.add_product(product_id=1, product_name=\"Widget\", qty=100)\n        self.assertEqual(self.inventory.get_product(product_id=1), {\"product_id\": 1, \"product_name\": \"Widget\", \"qty\": 100})\n\n    def test_update_product_qty(self):\n        self.inventory.add_product(product_id=1, product_name=\"Widget\", qty=100)\n        self.inventory.update_product_qty(product_id=1, qty_delta=10)\n        self.assertEqual(self.inventory.get_product(product_id=1)[\"qty\"], 110)\n\n    def test_get_product_not_found(self):\n        with self.assertRaises(ProductNotFoundError):\n            self.inventory.get_product(product_id=1)\n\n    def test_update_product_qty_insufficient_qty(self):\n        self.inventory.add_product(product_id=1, product_name=\"Widget\", qty=100)\n        with self.assertRaises(InsufficientQtyError):\n            self.inventory.update_product_qty(product_id=1, qty_delta=-110)\n            \nif __name__ == \"__main__\":\n    unittest.main()","metadata":{"execution":{"iopub.status.busy":"2023-01-11T08:16:32.979904Z","iopub.execute_input":"2023-01-11T08:16:32.980331Z","iopub.status.idle":"2023-01-11T08:16:33.003855Z","shell.execute_reply.started":"2023-01-11T08:16:32.980297Z","shell.execute_reply":"2023-01-11T08:16:33.001743Z"},"trusted":true},"execution_count":4,"outputs":[{"name":"stderr","text":"E\n======================================================================\nERROR: /root/ (unittest.loader._FailedTest)\n----------------------------------------------------------------------\nAttributeError: module '__main__' has no attribute '/root/'\n\n----------------------------------------------------------------------\nRan 1 test in 0.001s\n\nFAILED (errors=1)\n","output_type":"stream"},{"traceback":["An exception has occurred, use %tb to see the full traceback.\n","\u001b[0;31mSystemExit\u001b[0m\u001b[0;31m:\u001b[0m True\n"],"ename":"SystemExit","evalue":"True","output_type":"error"},{"name":"stderr","text":"/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3560: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n","output_type":"stream"}]},{"cell_type":"code","source":"import unittest\n\nclass TestAccountsPayable(unittest.TestCase):\n    def setUp(self):\n        self.accounts_payable = AccountsPayable()\n\n    def test_add_invoice(self):\n        self.accounts_payable.add_invoice(invoice_number=123, vendor_name=\"ACME Inc.\", amount=1000.00)\n        self.assertEqual(self.accounts_payable.get_invoice(invoice_number=123), {\"invoice_number\": 123, \"vendor_name\": \"ACME Inc.\", \"amount\": 1000.00})\n\n    def test_pay_invoice(self):\n        self.accounts_payable.add_invoice(invoice_number=123, vendor_name=\"ACME Inc.\", amount=1000.00)\n        self.accounts_payable.pay_invoice(invoice_number=123, amount=1000.00)\n        self.assertEqual(self.accounts_payable.get_invoice(invoice_number=123)[\"status\"], \"paid\")\n\n    def test_invalid_invoice(self):\n        with self.assertRaises(InvalidInvoiceError):\n            self.accounts_payable.pay_invoice(invoice_number=123, amount=1000.00)\nif __name__ == \"__main__\":\n    unittest.main()","metadata":{"execution":{"iopub.status.busy":"2023-01-11T08:17:40.134342Z","iopub.execute_input":"2023-01-11T08:17:40.135597Z","iopub.status.idle":"2023-01-11T08:17:40.154797Z","shell.execute_reply.started":"2023-01-11T08:17:40.135550Z","shell.execute_reply":"2023-01-11T08:17:40.153069Z"},"trusted":true},"execution_count":5,"outputs":[{"name":"stderr","text":"E\n======================================================================\nERROR: /root/ (unittest.loader._FailedTest)\n----------------------------------------------------------------------\nAttributeError: module '__main__' has no attribute '/root/'\n\n----------------------------------------------------------------------\nRan 1 test in 0.001s\n\nFAILED (errors=1)\n","output_type":"stream"},{"traceback":["An exception has occurred, use %tb to see the full traceback.\n","\u001b[0;31mSystemExit\u001b[0m\u001b[0;31m:\u001b[0m True\n"],"ename":"SystemExit","evalue":"True","output_type":"error"},{"name":"stderr","text":"/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3560: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n","output_type":"stream"}]}]}